import Link from "next/link"
import { notFound } from "next/navigation"
import { Star, Truck, ShieldCheck, BadgeCheck, ChevronLeft } from "lucide-react"
import { fetchGenericProduct } from "@/lib/generic-api"
import { productSaleInfo } from "@/lib/products"
import { ProductImageGallery } from "./components/ProductImageGallery"
import { ProductActionButtons } from "./components/ProductActionButtons"
import { ProductContactButtons } from "./components/ProductContactButtons"
import { ProductDescription } from "./components/ProductDescription"
import type { Metadata } from "next"
import { buildMetadata } from "@/lib/seo/metadata"
import { JsonLd } from "@/lib/seo/JsonLdComponent"
import { productSchema, breadcrumbSchema } from "@/lib/seo/jsonld"

/** Strip HTML tags for a clean meta description. */
function plainText(html?: string | null) {
  if (!html) return undefined
  return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim()
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  try {
    const { slug } = await params
    const data = await fetchGenericProduct(slug)
    const product = data.product
    if (!product) return buildMetadata({ title: "Listing not found", path: `/product/${slug}`, noindex: true })
    const price = new Intl.NumberFormat("en-NG", { style: "currency", currency: product.currency || "NGN", maximumFractionDigits: 0 }).format(product.price)
    // OG/Twitter image is generated by ./opengraph-image.tsx (branded card).
    return buildMetadata({
      title: product.name,
      description:
        plainText(product.description) ||
        `Buy ${product.name}${product.brand ? ` by ${product.brand}` : ""} from ${price} on Banex Mall — escrow protected, same-hour rider delivery.`,
      path: `/product/${product.slug}`,
      ogType: "product",
    })
  } catch {
    return buildMetadata({ title: "Product", path: "/shop", noindex: true })
  }
}

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  let data
  try {
    const resolvedParams = await params
    data = await fetchGenericProduct(resolvedParams.slug)
  } catch (err) {
    notFound()
  }

  if (!data?.product) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center px-4">
        <h1 className="font-display text-4xl">Listing not found</h1>
        <Link href="/shop" className="mt-4 text-brand hover:underline">
          ← Back to marketplace
        </Link>
      </div>
    )
  }

  const { product } = data
  // Banex Mall is the single seller — the product's own price is the price.
  const lowest = product.price
  // Strike through the regular price when an active sale is present (the catalog
  // must expose regular_price/sales_price for this to render).
  const sale = productSaleInfo(product)

  const formatNaira = (amount: number) => {
    return new Intl.NumberFormat("en-NG", {
      style: "currency",
      currency: "NGN",
      maximumFractionDigits: 0,
    }).format(amount)
  }

  // ── Structured data (Product + AggregateOffer + Breadcrumb) ──
  const productImages = (product.images || [])
    .slice()
    .sort((a, b) => Number(b.is_primary) - Number(a.is_primary))
    .map((img) => img.url)
  const jsonLd = [
    productSchema({
      name: product.name,
      slug: product.slug,
      description: product.description?.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim(),
      images: productImages,
      brand: product.brand,
      category: product.category?.name,
      currency: product.currency || "NGN",
      price: lowest,
      inStock: product.in_stock,
      ratingValue: product.rating_average,
      reviewCount: product.reviews_count,
      sellers: [{ name: "Banex Mall", price: product.price }],
    }),
    breadcrumbSchema([
      { name: "Home", path: "/" },
      { name: "Shop", path: "/shop" },
      ...(product.category
        ? [{ name: product.category.name, path: `/shop/${product.category.slug}` }]
        : []),
      { name: product.name, path: `/product/${product.slug}` },
    ]),
  ]

  return (
    <div>
      <JsonLd schema={jsonLd} />
      <div className="mx-auto max-w-7xl px-4 pt-4 md:px-8">
        <Link href="/shop" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-brand">
          <ChevronLeft className="h-4 w-4" /> Back to marketplace
        </Link>
      </div>

      <section className="mx-auto grid grid-cols-1 max-w-7xl gap-10 px-4 py-4 md:grid-cols-2 md:px-8 md:py-12">
        <ProductImageGallery images={product.images || []} name={product.name} />

        <div>
          <p className="text-xs uppercase tracking-widest text-brand-deep">
            {product.brand} · {product.category?.name || "Uncategorized"}
          </p>
          <h1 className="mt-3 font-display text-3xl font-bold md:text-5xl break-all">{product.name}</h1>
          <div className="mt-3 flex items-center gap-2 text-sm text-muted-foreground">
            <Star className="h-4 w-4 fill-brand text-brand" />
            <span className="text-foreground">{product.rating_average || "0.0"}</span>
            <span>· {(product.reviews_count || 0).toLocaleString()} reviews</span>
          </div>

          <div className="mt-6 flex items-end gap-3">
            <div>
              <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Price</p>
              <div className="flex flex-wrap items-baseline gap-2">
                <p className="font-display text-3xl font-bold text-foreground md:text-4xl">{formatNaira(lowest)}</p>
                {sale.onSale && (
                  <>
                    <span className="text-lg font-medium text-muted-foreground line-through md:text-xl">{formatNaira(sale.original!)}</span>
                    <span className="rounded-full bg-rose-600 px-2 py-0.5 text-xs font-bold text-white">−{sale.percentOff}%</span>
                  </>
                )}
              </div>
            </div>
            {product.in_stock ? (
              <span className="rounded-full border border-emerald-500/40 bg-emerald-500/10 px-3 py-1 text-xs font-medium text-emerald-700 dark:text-emerald-400">
                In stock
              </span>
            ) : (
              <span className="rounded-full border border-red-300 bg-red-100 px-3 py-1 text-xs font-medium text-red-600">
                Out of stock
              </span>
            )}
          </div>

          {/* Action buttons (client interactivity extracted) */}
          <ProductActionButtons product={product} />

          {/* Contact Banex Mall about this listing */}
          <ProductContactButtons product={product} />

          <div className="mt-8 flex flex-wrap gap-2 border-t border-border pt-6 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface px-3 py-1.5">
              <ShieldCheck className="h-3.5 w-3.5 text-brand" /> Escrow protected
            </span>
            <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface px-3 py-1.5">
              <Truck className="h-3.5 w-3.5 text-brand" /> Nationwide delivery
            </span>
            <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-surface px-3 py-1.5">
              <BadgeCheck className="h-3.5 w-3.5 text-brand" /> Authentic only
            </span>
          </div>
        </div>
      </section>

      {/* Product Description */}
      <section className="mx-auto max-w-7xl px-4 pb-12 md:px-8">
        <h2 className="mb-6 font-display text-xl font-bold md:text-2xl">Product Overview</h2>
        <ProductDescription html={product.description || null} />
      </section>

      {/* Specifications */}
      {product.specifications && product.specifications.length > 0 && (
        <section className="mx-auto max-w-7xl px-4 pb-20 md:px-8">
          <h2 className="mb-6 font-display text-xl font-bold md:text-2xl">Specifications</h2>
          <dl className="grid grid-cols-1 overflow-hidden rounded-2xl border border-border bg-card sm:grid-cols-2 lg:grid-cols-3">
            {product.specifications.map((spec, i) => {
              const [k, v] = spec.split("=>").map((s) => s.trim())
              return (
                <div key={i} className="border-b border-border p-4 last:border-b-0 sm:[&:nth-last-child(-n+1)]:border-b-0 md:even:border-l">
                  <dt className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">{k || "Detail"}</dt>
                  <dd className="mt-1 text-sm font-medium text-foreground">{v || spec}</dd>
                </div>
              )
            })}
          </dl>
        </section>
      )}
    </div>
  )
}
